# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: startsWith(github.event.head_commit.message, '[release]')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
        run: ./gradlew nativeImageZip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        if: success()
        with:
          tag: releases
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/dist/*
          file_glob: true
          overwrite: true
